CoM rotation and flip
LiberTEM/LiberTEM pull request #1087
Opened 2021-08-23 13:49 UTC by sk1p

Fixes #31 

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed

2021-08-23 15:36 UTC, uellue requested changes
Looks good so far! We should include a link or info sign that explains the parameters. We have them documented in https://libertem.github.io/LiberTEM/reference/api.html#libertem.api.Context.create_com_analysis, for example. :-)

With near-instantaneous recalculation after parameter change it would be awesome to have a slider for the angle, or a rotation handle on the widget for position and size!

I noticed that we don't have COM in our Applications section. We could perhaps create a stub for the "phase contrast" application with an API example, link to reference docs and one screenshot for COM, and a link to https://ptychography-4-0.github.io/ptychography/algorithms.html for SSB ptychography?

2021-08-23 15:36 UTC, uellue commented on .editorconfig
> +root = true
Is this file meant to be added?

2021-08-23 15:36 UTC, uellue commented on src/libertem/analysis/com.py
> +
OMG it recalculates live when I change the parameters without re-running the UDF? NICE! Can I have a slider for the angle, please? 😁

2021-08-23 15:42 UTC, uellue commented
- [ ] The template for notebook download should also be updated to include the new parameters.
- [ ] Fix results data download.

Current result when downloading:

2021-08-23 15:47 UTC, uellue commented
We could consider baking a new release soon after this?

2021-08-23 16:10 UTC, sk1p commented
> Looks good so far! We should include a link or info sign that explains the parameters. We have them documented in https://libertem.github.io/LiberTEM/reference/api.html#libertem.api.Context.create_com_analysis, for example. :-)

:+1: - I'll add more information about the parameters. I also thought about always showing the parameter form, as it doesn't take up a lot of space anyway - what do you think?

> Current result when downloading: [...]

Thanks, I'll look into that, should be easy to fix.

> We could consider baking a new release soon after this?

Yeah, I thought the same - what do you think about including a fix for #633, too, as I'm touching that code anyways?

> I noticed that we don't have COM in our Applications section. We could perhaps create a stub for the "phase contrast" application with an API example, link to reference docs and one screenshot for COM, and a link to https://ptychography-4-0.github.io/ptychography/algorithms.html for SSB ptychography?

Sure, I'll add a section to the docs.

2021-08-23 16:14 UTC, uellue commented
> > Looks good so far! We should include a link or info sign that explains the parameters. We have them documented in https://libertem.github.io/LiberTEM/reference/api.html#libertem.api.Context.create_com_analysis, for example. :-)
> 
> 👍 - I'll add more information about the parameters. I also thought about always showing the parameter form, as it doesn't take up a lot of space anyway - what do you think?

Yes, I was wondering why they were hidden but figured you had your reasons. 😆 
 
> > We could consider baking a new release soon after this?
> 
> Yeah, I thought the same - what do you think about including a fix for #633, too, as I'm touching that code anyways?

Yes, perfect! Would require a bit more change in the CoM API, but should be pretty straightforward, right? :-)

Other points: Thx, great! 👍

2021-08-23 18:46 UTC, sk1p commented
/azp run libertem.libertem-data

2021-08-23 20:01 UTC, sk1p commented
/azp run libertem.libertem-data

2021-08-24 13:44 UTC, sk1p commented
/azp run libertem.libertem-data

2021-08-24 14:13 UTC, sk1p commented
@uellue I've pushed the last fixes; if you are happy with this, I can re-build the client and merge - or do you want to push CoM docs also to this PR?

2021-08-24 15:54 UTC, uellue commented
> or do you want to push CoM docs also to this PR?

If it is OK it could be a quick solution! :-) I can also rebuild the client if I am at it. :-)

2021-08-24 15:55 UTC, sk1p commented
> If it is OK it could be a quick solution! :-) I can also rebuild the client if I am at it. :-)

Sounds good!

2021-08-24 18:17 UTC, uellue commented
/azp run libertem.libertem-data

2021-08-24 18:58 UTC, uellue approved these changes
Looks good, many thanks! :-)

Should be ready to merge now. :-)

2021-08-24 23:15 UTC, merged