Deprecate gridmatching and fullmatch
LiberTEM/LiberTEM pull request #1600
Opened 2024-02-22 14:27 UTC by uellue

Depends on releasing
https://github.com/LiberTEM/LiberTEM-blobfinder/pull/83, will fail and should not be merged until then.

Closes #1469

The tests are removed, which allows removing the test fixtures and corresponding imports, which then allows testing for a `DeprecationWarning` on import.

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed
* [ ] No import of GPL code from MIT code

2024-02-22 14:27 UTC, uellue commented
/azp run libertem.libertem-data

2024-02-22 16:47 UTC, uellue commented
/azp run libertem.libertem-data

2024-02-22 18:11 UTC, sk1p approved these changes
:+1: :+1: :+1:

As this will have to wait for a LiberTEM-blobfinder release, I'll include a very minimal version of this (just don't install `hdbscan`) in a separate PR, so we can benefit ASAP.

2024-02-22 18:11 UTC, sk1p commented on tox.ini
> -    hdbscan
This probably also has to be done for the `notebooks_gen` environment

2024-02-22 18:29 UTC, sk1p commented on docs_requirements.txt
>  hdbscan>=0.8.28
Do we need `hdbscan` for docs still?

```suggestion
```

2024-02-23 11:01 UTC, uellue commented on docs_requirements.txt
>  hdbscan>=0.8.28
No, actually! Thx good catch.

2024-04-11 09:59 UTC, sk1p requested changes
Thanks! Needs some small changes, specifically versions, then it's good to go (still needs the new blobfinder release though)

2024-04-11 09:59 UTC, sk1p commented on tox.ini
> +    libertem-blobfinder[hdbscan]
Needs a version constraint

2024-04-11 09:59 UTC, sk1p commented on tox.ini
> +    libertem-blobfinder[hdbscan]
Same as above, needs a version constraint

2024-04-11 09:59 UTC, sk1p commented on src/libertem/analysis/fullmatch.py
> +    'libertem_blobfinder.common.',
Can we put in a version where this will be removed?

2024-04-11 09:59 UTC, sk1p commented on docs/source/reference/app/strain.rst
> +   and will be removed in a later release.
Need to specify the version where it will be removed

2024-04-11 09:59 UTC, sk1p commented on docs/source/changelog/obsolescence/gridmatch.rst
> +  a deprecation warning and will be removed in a later release (:issue:`1469`, :pr:`1600`).
Need to specify the version where it will be removed

2024-04-17 14:39 UTC, sk1p commented on tox.ini
> +    libertem-blobfinder[hdbscan]
```suggestion
    libertem-blobfinder[hdbscan]>=0.6
```

2024-04-17 15:32 UTC, sk1p approved these changes
Looks ready modulo the docs failure :+1:

2024-04-18 07:58 UTC, uellue commented
/azp run libertem.libertem-data

2024-04-18 08:52 UTC, uellue commented
/azp run libertem.libertem-data

2024-04-18 09:06 UTC, merged