Make `get_results` lazy
LiberTEM/LiberTEM pull request #1632
Opened 2024-04-25 17:02 UTC by sk1p

In case `UDF.get_results` does any significant amount of work (like CoM with `regression=1`), it's wasteful to call it for every partial result, especially in the live case, and when using smaller partitions.

With this PR, if the downstream visualization doesn't access the `buffers` attribute on the results object, calling `get_results` is skipped and the overheads should be reduced significantly.

Another aspect is, in case of async iteration, we need to make sure that access to results is happening in a consistent way. This PR introduces a lock that is taken around both `merge` and `get_results` (actually the functions around them, such that we get consistent results across multiple UDFs), and in the async case, a copy is performed such that we don't get a reference to the buffers that will be modified with the next `merge` call.

## TODOs:

- [x] How to make this thread-safe - we need to prevent the delayed `get_results` and the `merge` function from running concurrently on the same data / buffers, basically.
- [x] Needs documentation on how to safely access the results of `run_udf_iter`
- [x] This slightly changes the observed behavior, as seen in the failing test cases. I think this should be OK and the tests and the docs need to be updated, but some input would be welcome! This is mostly an issue if `get_results` has observable side-effects

Fixes #1596

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed
* [ ] No import of GPL code

2025-02-19 11:44 UTC, sk1p commented
@matbryan52 @uellue if one of you has some time to look over these changes I'd be grateful! CI failure on Python 3.13 is discussed over in #1697 and is unrelated to the changes here.

2025-02-19 12:02 UTC, uellue requested changes
Looks like a nice improvement, generally! I have questions regarding what actually happens here, see detailed comments. :-)

2025-02-19 12:02 UTC, uellue commented on src/libertem/udf/base.py
> +                    buffers.append(udf_res)
Also, I find it hard to understand the sequence of events with the async execution and lazy results. If I see this correctly, this will first give the user a handle for the lazy results `UDFResultsLazy`. That includes a reference to the original buffers that will change over time, right?

When the user actually accesses the buffers, it will call the `_inner()` function, get a lock and take the copy from the result buffers _at that time_, which could be a later state than the position in the iterator. The advantage of that is that we only take a copy when it is needed. Disadvantage is that we get a pretty undefined sample of the state of the iteration engine that is not related to the position in the iterator, unlike the sync case.

An alternative implementation could be to give the user a handle to request a current copy of the state of the result buffers, also calling `get_results()`, instead of using an async iterator. With that it would be clear that the returned value is whatever the state is at the time the lock is acquired.

2025-02-19 12:08 UTC, uellue commented on src/libertem/udf/base.py
> +                    buffers.append(udf_res)
To keep the API consistent between the sync and async case one should take the copy immediately with lock, and call `get_results()` lazily on that copy, right? The efficient interface, if desired, would be an addition, I guess?

2025-02-19 12:09 UTC, sk1p commented on src/libertem/udf/base.py
> +                    buffers.append(udf_res)
> The `get_results()` function is called in `udf._do_get_results()`, right? Since that can be expensive for methods like iCoM, would it be possible to first take a copy of the result buffers, release the lock, and then call `udf._do_get_results()` in such a way that it accesses the copied buffers instead of the originals?

Yes, that should also be possible, and should reduce the time we keep things locked :+1:

> Also, I find it hard to understand the sequence of events with the async execution and lazy results [...]

Your understanding seems to be correct. Factually, even in our currently released version, the async iteration can basically only access the latest result (as we only reference the result buffers in each iteration step, so the merge of the next iteration might have already been called etc....). 

Adding a different API for this would not be a bad idea; I'll have to think about about how this should look like.

2025-02-19 12:14 UTC, sk1p commented on src/libertem/udf/base.py
> +                    buffers.append(udf_res)
> To keep the API consistent between the sync and async case one should take the copy immediately with lock, and call `get_results()` lazily on that copy, right? The efficient interface, if desired, would be an addition, I guess?

We can do it like that, I have a feeling that we may need to assess the performance overhead with a benchmark and some profiling... especially for small partition sizes, there would be a lot of memory turnover. If it turns out to be an issue, we may want to deprecate the slow API.

2025-02-25 13:18 UTC, sk1p commented on src/libertem/udf/base.py
> +                    buffers.append(udf_res)
Short sketch of the new API, with control over when the results are (consistently) fetched:

```python
# `x` is just a dummy parameter, so we have something to update:
x = 0

# start the UDF run; push parameters to workers etc.:
async with ctx.run_udf_async(dataset=ds, udf=MyUDF(x=x)) as run:
    # get an iterable of update notifications, and iterate over it.
    # the next `update` you get, 
    async for update in run.updates():
        # fetch the _latest_ results from the run in the background
        # (consistently, preventing a concurrent `merge`):
        # XXX `get_latest` makes a copy, and `.buffers` calls `get_results` on that copy
        latest_result = run.get_latest()
        # just for completeness, push a parameter into the current run:
        await run.update_parameters_experimental([{"x": x}])
        x += 1
# the updates generator is always closed here, after the `with`-block, even in case of errors
# (which was not the case for the previous API, where you need to explicitly close or use `contextlib.closing`)
```

2025-02-26 15:56 UTC, sk1p commented on src/libertem/udf/base.py
> +                    buffers.append(udf_res)
Make sure that the non-iterative versions of the API only calls `get_results` on the final update. 

Use-case for non-expert users: make snippets like this skip `get_results` calls, too (in the synchronous case):

```python
res_iter = ctx.run_udf_iter(..., sync=True)
for item in res_iter:
    send_to_queue(item)  # on the other end, you can skip items, and call .buffers on those results 
```

In the future, we can also provide a sync API that under the hood runs the iterators in a background thread, but can skip results etc. for the user, or provide a queue-like interface.

Note to self: does `run.get_latest()` need to be async, to wait for the lock?

2025-03-26 10:08 UTC, uellue commented on src/libertem/udf/base.py
> +                    buffers.append(udf_res)
LGTM! a small suggestion, in actual example code one could write `async for _ in run.updates():` to make clearer that the update is just a "ping". :-)

2025-03-26 15:59 UTC, uellue commented
Bumped to next milestone since this will need some QA

2026-02-03 17:13 UTC, sk1p commented
/azp run libertem.libertem-data

2026-02-03 17:25 UTC, sk1p commented
CI failure in example notebooks is same as #1791 - so I'll rebase once that is merged.

2026-02-04 11:16 UTC, uellue commented
Notebook failure is on Python 3.9, will merge #1791, rebase and retest after CI finishes there.

2026-02-04 11:17 UTC, uellue commented
> CI failure in example notebooks is same as #1791 - so I'll rebase once that is merged.

LOL didn't read before writing...

2026-02-04 16:30 UTC, sk1p commented
/azp run libertem.libertem-data

2026-02-05 16:33 UTC, uellue commented
The live server example does not error out with this PR, but still shows the grey results after the first pass. I've tried to reduce the update rate in the GUI and also trigger manually to give the system time to empty queues, but sth is still missing in the code!

2026-05-18 11:34 UTC, sk1p commented
/azp run libertem.libertem-data

2026-05-18 14:36 UTC, merged