Move to hatchling for build + `pyproject.toml` for package def
LiberTEM/LiberTEM pull request #1667
Opened 2024-06-27 14:38 UTC by matbryan52

Closes #1641. WIP to see how angry CI is at me for pulling the rug out from under it.

- Moves project definition into `pyproject.toml` and use `hatchling` as backend
- Remove `setup.cfg` by moving config options to other files as appropriate
- Move the `build_client` and `copy_client` commands into a dedicated script with `click` for CLI
- Remove `setup.py`
- Use https://github.com/ofek/hatch-vcs as plugin to generate `__version__` and `revision` from tags. I don't like that the normal version number now has the git revision in it, I need to look more into this plugin to see how to configure it.

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed
* [x] No import of GPL code from MIT code

2024-06-27 15:12 UTC, sk1p commented
> * [ ]  I don't like that the normal version number now has the git revision in it, I need to look more into this plugin to see how to configure it.

You can also check how this is done for LiberTEM-live, which uses a custom `hatch_build.py` for baking the revision, and `tool.hatch.version` for reading the version from `__version__.py`  (basically keeps the old way of versioning, just with new packaging around it)

2024-06-28 09:54 UTC, matbryan52 commented
/azp run libertem.libertem-data

2024-06-28 10:13 UTC, matbryan52 commented
> > * [ ]   I don't like that the normal version number now has the git revision in it, I need to look more into this plugin to see how to configure it.
> 
> You can also check how this is done for LiberTEM-live, which uses a custom `hatch_build.py` for baking the revision, and `tool.hatch.version` for reading the version from `__version__.py` (basically keeps the old way of versioning, just with new packaging around it)

Great, my fault for not looking too closely at the way you set it up over there. I've followed the same pattern here! Thanks for the tip.

2024-06-28 10:49 UTC, matbryan52 commented
/azp run libertem.libertem-data

2024-07-04 13:08 UTC, sk1p requested changes
:+1: looks good overall. One major thing: the wheel and sdist (built with `python -m build --sdist --wheel`) don't seem to include `_baked_revision.py`. Not sure why yet...

2024-07-04 13:27 UTC, matbryan52 commented on tox.ini
> +    pytest --doctest-modules --ignore=src/libertem/common/win_tweaks.py --ignore=src/libertem/_baked_revision.py --ignore=src/libertem/analysis/fullmatch.py src/libertem/
I was getting CI failures for lack of coverage information on `_baked_revision.py`. I will try removing it again now that the _baked_revision is in the sdist.

2024-07-04 13:44 UTC, matbryan52 commented on tox.ini
> +    pytest --doctest-modules --ignore=src/libertem/common/win_tweaks.py --ignore=src/libertem/_baked_revision.py --ignore=src/libertem/analysis/fullmatch.py src/libertem/
Still failing when I don't ignore `_baked_revision.py` in doctest-modules : https://github.com/LiberTEM/LiberTEM/actions/runs/9795236694/job/27046926599?pr=1667

2024-07-04 13:45 UTC, sk1p commented on tox.ini
> +    pytest --doctest-modules --ignore=src/libertem/common/win_tweaks.py --ignore=src/libertem/_baked_revision.py --ignore=src/libertem/analysis/fullmatch.py src/libertem/
Yeah - it's weird because IIRC this doesn't happen in LiberTEM-live...

2024-07-04 13:47 UTC, sk1p commented on tox.ini
> +    pytest --doctest-modules --ignore=src/libertem/common/win_tweaks.py --ignore=src/libertem/_baked_revision.py --ignore=src/libertem/analysis/fullmatch.py src/libertem/
Might still be a difference between what's installed in the test environment vs. what's in the source tree?

2024-07-04 13:48 UTC, sk1p commented on tox.ini
> +    pytest --doctest-modules --ignore=src/libertem/common/win_tweaks.py --ignore=src/libertem/_baked_revision.py --ignore=src/libertem/analysis/fullmatch.py src/libertem/
Yeah, sdist includes the baked revision, the wheel doesn't?

2024-07-04 13:49 UTC, sk1p commented on tox.ini
> +    pytest --doctest-modules --ignore=src/libertem/common/win_tweaks.py --ignore=src/libertem/_baked_revision.py --ignore=src/libertem/analysis/fullmatch.py src/libertem/
```diff
diff --git a/pyproject.toml b/pyproject.toml
index c715e6fa..bd50fd93 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -111,6 +111,11 @@ Homepage = "https://libertem.github.io/LiberTEM/"
 [tool.hatch.version]
 path = "src/libertem/__version__.py"
 
+[tool.hatch.build.targets.wheel]
+artifacts = [
+    "/src/libertem/_baked_revision.py",
+]
+
 [tool.hatch.build.targets.sdist]
 artifacts = [
     "/src/libertem/_baked_revision.py",
@@ -181,4 +186,4 @@ exclude_lines = [
     "if 0:",
     "if False:",
     "if __name__ == .__main__.:",
```
?

2024-07-04 13:49 UTC, matbryan52 commented on tox.ini
> +    pytest --doctest-modules --ignore=src/libertem/common/win_tweaks.py --ignore=src/libertem/_baked_revision.py --ignore=src/libertem/analysis/fullmatch.py src/libertem/
OK, I will find the right magic words :D

2024-07-04 14:31 UTC, matbryan52 commented
/azp run libertem.libertem-data

2024-07-04 14:45 UTC, sk1p approved these changes
LGTM!

2024-07-04 14:45 UTC, merged