Add BLO 16bit support
LiberTEM/LiberTEM pull request #1676
Opened 2024-09-20 14:12 UTC by matbryan52

Adds support for a new Blockfile format (1.3) which can store image data in 16bit mode.

The implementation is conservative, falling back to the old 8bit assumption if the metadata does not match what we expect.

I have uploaded a test file "Stingray16bit_7_11.blo" into the root of the test data folder in the DMS.

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed
* [x] No import of GPL code from MIT code

2024-09-20 14:20 UTC, matbryan52 commented
/azp run libertem.libertem-data

2024-09-21 13:21 UTC, sk1p requested changes
Thanks for the PR - two small issues commented inline; CI should be fixed by a rebase on `master`. Looking good otherwise!

2024-09-21 13:21 UTC, sk1p commented on docs/source/changelog/features/blo-16bit.rst
> +  image data accordingly (:pr:`1631`).
```suggestion
  image data accordingly (:pr:`1676`).
```

2024-09-21 13:21 UTC, sk1p commented on src/libertem/io/dataset/blo.py
> +                metadata_bytes = f.read(data_start_byte - metadata_start_pos)
Note for myself: `f` is a `BufferedIOBase`, where `read` won't return short reads

2024-09-21 13:21 UTC, sk1p commented on src/libertem/io/dataset/blo.py
> +    def _try_read_bitdepth(metadata: tuple[str]) -> str:
```suggestion
    def _try_read_bitdepth(metadata: tuple[str, ...]) -> str:
```

`tuple[str]` is a tuple with a single element; for example:


```python
def f(t: tuple[str]):
    pass

f(("a",))
f(("a", "b", "c"))  # <- mypy: error: Argument 1 to "f" has incompatible type "tuple[str, str, str]"; expected "tuple[str]"  [arg-type]


def g(t: tuple[str, ...]):
    pass

g(("a",))
g(("a", "b", "c"))  # this is fine
```

2024-09-23 06:54 UTC, sk1p commented
/azp run libertem.libertem-data

2024-09-23 06:54 UTC, matbryan52 commented
/azp run libertem.libertem-data

2024-09-23 07:03 UTC, matbryan52 commented
> Thanks for the PR - two small issues commented inline; CI should be fixed by a rebase on `master`. Looking good otherwise!

Thanks for the review !

2024-09-23 07:35 UTC, merged